### ISSUE TITLE
visual-genome-features

### ISSUE THREAD

**Issue by jinlianchao185874** [BierOne/genome-rcnn-features-for-bottom-up#1]
Hi, BierOne. I run your repo relation-vqa which is a perfect work.But the relation-fact-detector needs the visual-genome-features.Would you please send me the processing image feature file? It can be paid，much thanks. you can concat me with 
 vx jlc185874

**Comment by BierOne** [comment]
Hi lianchao. I’m so sorry for the late response as I was overwhelmed in the last several months. The good thing is that I have extracted genome features today. And if you still need this feature file, please contact me.
